export const buttonsArray = [
  {"id": "c", "className": "operator", "function": (funcao) => {funcao()}},
  {"id": "+/-", "className": "operator", "function": (funcao) => {funcao()}},
  {"id": "%", "className": "operator", "function": (funcao) => {funcao()}},
  {"id": "/", "className": "operator", "function": (funcao) => {funcao()}},
  {"id": "7", "className": "number", "function": null},
  {"id": "8", "className": "number", "function": null},
  {"id": "9", "className": "number", "function": null},
  {"id": "x", "className": "operator", "function": (funcao) => {funcao()}},
  {"id": "4", "className": "number", "function": null},
  {"id": "5", "className": "number", "function": null},
  {"id": "6", "className": "number", "function": null},
  {"id": "-", "className": "operator", "function": (funcao) => {funcao()}},
  {"id": "1", "className": "number", "function": null},
  {"id": "2", "className": "number", "function": null},
  {"id": "3", "className": "number", "function": null},
  {"id": "+", "className": "operator", "function": (funcao) => {funcao()}},
  {"id": "0", "className": "number", "function": null},
  {"id": ".", "className": "number", "function": null},
  {"id": "", "className": "number", "function": null},
]